const fs = require('fs');
const path = require('path');

const agentsDir = path.join(__dirname, '..', 'agents');

function vidUrl(id) {
  return id && id !== 'TBD' ? `https://play.vidyard.com/${id}` : '';
}

const agents = [

  // ── APPAREL NEXT GEN ─────────────────────────────────────────────────────────

  {
    id: 'product-info-sheet-tech-pack',
    name: 'Product Info Sheet from Tech Pack',
    tagline: 'Auto-generate five customer-ready deliverables from uploaded Tech Pack PDFs',
    description: 'Analyzes uploaded Tech Pack PDFs and automatically generates five customer-ready deliverables—Product Info Sheet, Retail Sell Sheet, E-commerce Description, Line Sheet, and Size & Fit Guide—eliminating hours of manual copywriting per style.',
    industry: ['Apparel'], function: 'Style Management', productLine: 'Apparel Next Gen',
    status: 'live', flowId: 'placeholder',
    tags: ['Tech Pack', 'PDF', 'Copywriting', 'Style'],
    emoji: '👗', iconBg: '#FDF2F8',
    rating: 4.7, reviews: [], usageCount: 38,
    videoUrl: vidUrl('JEGEc5zR3CDVUUZve2sCVq'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'style-description-bc',
    name: 'Style Description Agent',
    tagline: 'Generate polished product names and marketing descriptions from Style Card details',
    description: 'Generates polished product names and marketing-ready short descriptions directly from Style Card details, ensuring consistent brand voice across the entire product catalog.',
    industry: ['Apparel'], function: 'Style Management', productLine: 'Apparel Next Gen',
    status: 'live', flowId: 'placeholder',
    tags: ['Style Card', 'Business Central', 'Copywriting'],
    emoji: '✍️', iconBg: '#FDF2F8',
    rating: 4.6, reviews: [], usageCount: 52,
    videoUrl: vidUrl('cEtzdePpuXn9X8oiBQbydf'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'style-performance-analyzer',
    name: 'Style Performance Analyzer',
    tagline: 'Surface style-level performance signals across sales, margin, and inventory',
    description: 'Surfaces style-level performance signals across sales, margin, and inventory data to deliver actionable insights that improve sell-through, inventory turnover, and seasonal exit decisions.',
    industry: ['Apparel'], function: 'Analytics', productLine: 'Apparel Next Gen',
    status: 'live', flowId: 'placeholder',
    tags: ['Sales', 'Margin', 'Inventory', 'Sell-Through'],
    emoji: '📈', iconBg: '#E6F1FB',
    rating: 4.8, reviews: [], usageCount: 44,
    videoUrl: vidUrl('q6vsshobpvHDc9VA7LCqGJ'), docsUrl: '', reviewLinks: [], featured: true,
  },
  {
    id: 'style-substitution-bc',
    name: 'Style Substitution Agent (BC)',
    tagline: 'Recommend substitute styles instantly when items are out of stock or discontinued',
    description: 'Recommends substitute styles by matching Style Card attributes and validating price range compatibility, helping merchandisers respond instantly when items are out of stock or discontinued.',
    industry: ['Apparel'], function: 'Style Management', productLine: 'Apparel Next Gen',
    status: 'live', flowId: 'placeholder',
    tags: ['Style Card', 'Substitution', 'Business Central'],
    emoji: '🔄', iconBg: '#FDF2F8',
    rating: 4.5, reviews: [], usageCount: 31,
    videoUrl: vidUrl('4yy24uGChaSh556XTU1S5q'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'style-substitution-standalone',
    name: 'Style Substitution Agent (Standalone)',
    tagline: 'Style substitution intelligence for teams outside Business Central',
    description: 'Matches Style Card attributes and validates price range to recommend substitute styles through a standalone interface, giving teams outside of Business Central the same substitution intelligence.',
    industry: ['Apparel'], function: 'Style Management', productLine: 'Apparel Next Gen',
    status: 'live', flowId: 'placeholder',
    tags: ['Substitution', 'Standalone', 'Style'],
    emoji: '🔄', iconBg: '#FDF2F8',
    rating: 4.4, reviews: [], usageCount: 24,
    videoUrl: vidUrl('SQDtvSHAinJ1CZjwr6Th7a'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'style-tags-bc',
    name: 'Style Tags Agent',
    tagline: 'Auto-generate product attribute tags from style details and images',
    description: 'Automatically generates product attribute tags from style details, descriptions, category data, and product images—ensuring consistent, searchable metadata without manual data entry.',
    industry: ['Apparel'], function: 'Style Management', productLine: 'Apparel Next Gen',
    status: 'live', flowId: 'placeholder',
    tags: ['Tags', 'Metadata', 'Style Card', 'Images'],
    emoji: '🏷️', iconBg: '#FDF2F8',
    rating: 4.6, reviews: [], usageCount: 47,
    videoUrl: vidUrl('x7XvMLJnE3Jk2TVYkLncKW'), docsUrl: '', reviewLinks: [], featured: false,
  },

  // ── APTEAN FOOD & BEVERAGE ERP ────────────────────────────────────────────────

  {
    id: 'vendor-scorecard',
    name: 'Vendor Scorecard Agent',
    tagline: 'Score and rank vendors on delivery, quality, and cost to reduce supplier risk',
    description: 'Scores and ranks vendors on delivery performance, quality, and cost so planning managers can make faster, data-driven purchasing decisions and reduce supplier risk.',
    industry: ['Food & Beverage'], function: 'Procurement', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Vendor', 'Scorecard', 'Procurement', 'Risk'],
    emoji: '🏆', iconBg: '#FAEEDA',
    rating: 4.8, reviews: [], usageCount: 63,
    videoUrl: vidUrl('8LF1N9NgmQhodDXzJKkyK3'), docsUrl: '', reviewLinks: [], featured: true,
  },
  {
    id: 'dynamic-planning-forecasting',
    name: 'Dynamic Planning and Forecasting Agent',
    tagline: 'Replicate MPS/MRP to generate optimal supply plans through natural conversation',
    description: 'Replicates the MPS/MRP planning engine to generate, validate, and execute optimal supply plans—converting demand signals into actionable purchase orders, production orders, and transfers through natural conversation.',
    industry: ['Food & Beverage'], function: 'Supply Chain / Planning', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['MPS', 'MRP', 'Forecasting', 'Supply Plan'],
    emoji: '📦', iconBg: '#E1F5EE',
    rating: 4.9, reviews: [], usageCount: 89,
    videoUrl: vidUrl('wPsQfBGbQJN94nZrgcfiFW'), docsUrl: '', reviewLinks: [], featured: true,
  },
  {
    id: 'pick-generator',
    name: 'Pick Generator Agent',
    tagline: 'Generate optimized warehouse pick lists based on configurable business rules',
    description: 'Generates optimized warehouse pick lists based on configurable business rules, reducing pick time and improving order accuracy for warehouse teams.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Warehouse', 'Pick List', 'Fulfillment'],
    emoji: '📋', iconBg: '#E1F5EE',
    rating: 4.7, reviews: [], usageCount: 55,
    videoUrl: vidUrl('RA45iYWy987o1wKepNriqm'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'production-efficiency',
    name: 'Production Efficiency Agent',
    tagline: 'Identify production variances with root-cause analysis and correction recommendations',
    description: 'Identifies and explains production variances—material consumption, yield loss, scrap, and labor inefficiencies—with traceable root-cause analysis and actionable BOM and routing correction recommendations.',
    industry: ['Food & Beverage'], function: 'Quality / RCA', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Production', 'Variance', 'BOM', 'Yield'],
    emoji: '🏭', iconBg: '#FCEBEB',
    rating: 4.8, reviews: [], usageCount: 71,
    videoUrl: vidUrl('J5PDYtM3YnPgcuE87vGdgM'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'regulatory-compliance-audit',
    name: 'Regulatory Compliance Audit Agent',
    tagline: 'Compile and validate compliance evidence for continuous audit readiness',
    description: 'Compiles, validates, and exports compliance evidence across suppliers, production, QC, allergen control, and traceability to ensure continuous audit readiness and reduce manual documentation effort.',
    industry: ['Food & Beverage'], function: 'Compliance', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Compliance', 'Audit', 'Allergen', 'QC'],
    emoji: '🛡️', iconBg: '#FCEBEB',
    rating: 4.9, reviews: [], usageCount: 48,
    videoUrl: vidUrl('LNmfWyc4Qb648TzCKANagS'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'sales-push-expiration',
    name: 'Sales Push Agent',
    tagline: 'Identify expiring inventory, optimize pricing, and protect margin from waste',
    description: 'Identifies inventory nearing expiration, cross-references live market shortage data to optimize pricing, and outputs item-level price recommendations that protect margin and reduce waste.',
    industry: ['Food & Beverage'], function: 'Sales / CRM', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Expiration', 'Pricing', 'Inventory', 'Margin'],
    emoji: '⏱️', iconBg: '#FBEAF0',
    rating: 4.7, reviews: [], usageCount: 42,
    videoUrl: vidUrl('AfyeK6eNFjCV2V2Ys3PYfX'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'rca-agent',
    name: 'Root Cause Analysis (RCA) Agent',
    tagline: 'Diagnose quality failures with structured root-cause analysis workflows',
    description: 'Guides quality and operations teams through structured root-cause analysis for production failures, non-conformances, and customer complaints—surfacing corrective actions and preventing recurrence.',
    industry: ['Food & Beverage'], function: 'Quality / RCA', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['RCA', 'Quality', 'Non-conformance', 'CAPA'],
    emoji: '🔬', iconBg: '#FCEBEB',
    rating: 4.8, reviews: [], usageCount: 61,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'recall-trace',
    name: 'Recall and Trace Agent',
    tagline: 'Execute forward and backward lot traceability for rapid recall response',
    description: 'Executes forward and backward lot traceability across the supply chain, instantly identifying affected batches, customers, and suppliers to support rapid recall response and regulatory reporting.',
    industry: ['Food & Beverage'], function: 'Traceability', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Recall', 'Lot Traceability', 'FSMA', 'Batch'],
    emoji: '🔗', iconBg: '#E0F5F5',
    rating: 4.9, reviews: [], usageCount: 77,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: true,
  },
  {
    id: 'auto-order',
    name: 'Auto Order Agent',
    tagline: 'Automatically generate purchase orders from demand signals and reorder rules',
    description: 'Automatically generates purchase orders based on demand signals, reorder point rules, and supplier lead times—reducing manual procurement effort and preventing stockouts.',
    industry: ['Food & Beverage'], function: 'Procurement', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Purchase Orders', 'Reorder', 'Automation'],
    emoji: '🛒', iconBg: '#FAEEDA',
    rating: 4.6, reviews: [], usageCount: 53,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'close-production-order',
    name: 'Close Production Order Agent',
    tagline: 'Validate, approve, and close released production orders through an 8-stage lifecycle',
    description: 'Validates, approves, and closes released production orders on Microsoft Dynamics 365 Business Central. Runs an 8-stage lifecycle that identifies candidate orders, validates output/consumption/routing/warehouse completeness, triages exceptions, routes fixes, finishes the order, and notifies stakeholders.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Production Order', 'Close', 'Validation', 'Business Central'],
    emoji: '✅', iconBg: '#E1F5EE',
    rating: 4.7, reviews: [], usageCount: 39,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'accounts-payable',
    name: 'Accounts Payable (AP) Agent',
    tagline: 'Streamline AP workflows with intelligent invoice matching and payment insights',
    description: 'Streamlines accounts payable workflows by matching invoices to purchase orders, flagging discrepancies, tracking payment due dates, and surfacing cash flow insights to reduce late payments and improve vendor relationships.',
    industry: ['Food & Beverage'], function: 'Finance / AR', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Accounts Payable', 'Invoice', 'Payment', 'AP'],
    emoji: '💰', iconBg: '#EEEDFE',
    rating: 4.6, reviews: [], usageCount: 44,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'purchasing-agent-fb',
    name: 'Purchasing Agent',
    tagline: 'Manage the purchase order workspace and keep supply timelines on track',
    description: 'Manages the purchase order workspace by flagging late POs, sending supplier reminders, and surfacing actionable procurement tasks to keep supply timelines on track.',
    industry: ['Food & Beverage'], function: 'Procurement', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Purchase Orders', 'Procurement', 'Supplier'],
    emoji: '🛒', iconBg: '#FAEEDA',
    rating: 4.5, reviews: [], usageCount: 36,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'recipe-formulation-costing',
    name: 'Recipe Formulation Costing Agent',
    tagline: 'Calculate and optimize recipe costs across ingredients and formulation scenarios',
    description: 'Calculates and compares recipe formulation costs across ingredient alternatives, yield scenarios, and batch sizes—helping R&D and operations teams make cost-effective formulation decisions without leaving their workflow.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Recipe', 'Formulation', 'Costing', 'BOM'],
    emoji: '🧪', iconBg: '#E1F5EE',
    rating: 4.7, reviews: [], usageCount: 41,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'sales-agent',
    name: 'Sales Agent',
    tagline: 'Accelerate F&B sales with order insights, customer history, and opportunity alerts',
    description: 'Accelerates food and beverage sales by surfacing customer order history, open opportunities, product recommendations, and market trend alerts—helping sales teams close faster and grow accounts.',
    industry: ['Food & Beverage'], function: 'Sales / CRM', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Sales', 'Customer History', 'Opportunities'],
    emoji: '🤝', iconBg: '#FBEAF0',
    rating: 4.6, reviews: [], usageCount: 58,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'warehouse-inventory-rca',
    name: 'Warehouse Inventory RCA Agent',
    tagline: 'Diagnose warehouse inventory discrepancies with root-cause analysis',
    description: 'Diagnoses warehouse inventory discrepancies, shrinkage, and cycle count variances with structured root-cause analysis—surfacing process gaps and recommending corrective actions to restore inventory accuracy.',
    industry: ['Food & Beverage'], function: 'Quality / RCA', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Warehouse', 'Inventory', 'RCA', 'Cycle Count'],
    emoji: '🏭', iconBg: '#FCEBEB',
    rating: 4.7, reviews: [], usageCount: 33,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'accounts-receivable',
    name: 'Accounts Receivable (AR) Agent',
    tagline: 'Real-time AR analysis, aging reports, and customer payment behavior insights',
    description: 'Provides real-time AR analysis, aging reports, overdue invoice tracking, and customer payment behavior insights. Transforms raw receivables data into actionable collection intelligence and cash flow forecasts.',
    industry: ['Food & Beverage'], function: 'Finance / AR', productLine: 'Aptean Food & Beverage ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['AR', 'Aging', 'Collections', 'Cash Flow'],
    emoji: '💳', iconBg: '#EEEDFE',
    rating: 4.8, reviews: [], usageCount: 67,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'planning-by-attribute',
    name: 'Planning by Attribute Agent',
    tagline: 'Run demand planning filtered by item attributes for better segmented forecasts',
    description: 'Enables planners to run demand planning filtered and grouped by item attributes, delivering more accurate segmented forecasts and replenishment plans across complex product portfolios.',
    industry: ['Food & Beverage'], function: 'Supply Chain / Planning', productLine: 'Aptean Food & Beverage ERP',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Planning', 'Attributes', 'Forecasting', 'Segmentation'],
    emoji: '📦', iconBg: '#E1F5EE',
    rating: 4.6, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'safety-stock-analysis-fb',
    name: 'Safety Stock Analysis Agent',
    tagline: 'Calculate and monitor safety stock levels tailored to F&B volatility',
    description: 'Calculates, monitors, and recommends safety stock levels across SKUs and locations, tailored to food and beverage volatility and perishability constraints.',
    industry: ['Food & Beverage'], function: 'Supply Chain / Planning', productLine: 'Aptean Food & Beverage ERP',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Safety Stock', 'F&B', 'Perishability', 'SKU'],
    emoji: '📊', iconBg: '#E1F5EE',
    rating: 4.6, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },

  // ── LASCOM PLM ────────────────────────────────────────────────────────────────

  {
    id: 'interactive-user-guide-lascom',
    name: 'Interactive User Guide Agent',
    tagline: 'Always-available guide for Lascom PLM navigation, features, and workflows',
    description: 'Serves as an always-available interactive guide embedded in Lascom PLM, answering user questions about system navigation, features, and workflows in real time.',
    industry: ['Food & Beverage', 'Life Sciences'], function: 'Operations', productLine: 'Lascom PLM',
    status: 'live', flowId: 'placeholder',
    tags: ['Lascom', 'PLM', 'User Guide', 'Navigation'],
    emoji: '📖', iconBg: '#E6F1FB',
    rating: 4.7, reviews: [], usageCount: 29,
    videoUrl: vidUrl('d69UQSjvjCqrDU6Hm4JSNM'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'product-improvement-lascom',
    name: 'Product Improvement Agent',
    tagline: 'Optimize formulations for quality and cost using recipe and nutritional analysis',
    description: 'Analyzes finished-good recipes, ingredients, additives, and nutritional profiles to suggest formulation optimizations that improve product quality while reducing input costs.',
    industry: ['Food & Beverage', 'Life Sciences'], function: 'Quality / RCA', productLine: 'Lascom PLM',
    status: 'live', flowId: 'placeholder',
    tags: ['Formulation', 'Recipe', 'PLM', 'Nutrition'],
    emoji: '🧬', iconBg: '#E6F1FB',
    rating: 4.8, reviews: [], usageCount: 35,
    videoUrl: vidUrl('S6pMKSR8VB5aU9tbUggrM2'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'product-information-translator',
    name: 'Product Information Translator Agent',
    tagline: 'Translate product texts and ingredient statements into required export languages',
    description: 'Translates product texts—including ingredient statements—into all required export languages, ensuring regulatory-compliant labeling ready for international markets.',
    industry: ['Food & Beverage', 'Life Sciences'], function: 'Compliance', productLine: 'Lascom PLM',
    status: 'live', flowId: 'placeholder',
    tags: ['Translation', 'Labeling', 'Compliance', 'Export'],
    emoji: '🌍', iconBg: '#E6F1FB',
    rating: 4.6, reviews: [], usageCount: 27,
    videoUrl: vidUrl('S6pMKSR8VB5aU9tbUggrM2'), docsUrl: '', reviewLinks: [], featured: false,
  },

  // ── TLX ──────────────────────────────────────────────────────────────────────

  {
    id: 'hts-code-lookup',
    name: 'HTS Code Lookup Agent',
    tagline: 'Determine accurate Harmonized Tariff Schedule codes for customs classification',
    description: 'Determines the most accurate Harmonized Tariff Schedule code for a given product description, streamlining customs classification and reducing compliance risk on international shipments.',
    industry: ['Food & Beverage', 'Apparel'], function: 'Compliance', productLine: 'TLX',
    status: 'live', flowId: 'placeholder',
    tags: ['HTS', 'Customs', 'Tariff', 'Classification'],
    emoji: '🚢', iconBg: '#E0F5F5',
    rating: 4.7, reviews: [], usageCount: 52,
    videoUrl: vidUrl('MX7ZGsTUaCRZFdHLhBYtt9'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'nmfc-lookup',
    name: 'NMFC Lookup Agent',
    tagline: 'Determine accurate NMFC commodity codes for domestic freight classification',
    description: 'Determines the most accurate NMFC commodity code for domestic freight, reducing classification errors and helping shippers secure correct carrier rates.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'TLX',
    status: 'live', flowId: 'placeholder',
    tags: ['NMFC', 'Freight', 'Classification', 'Carrier'],
    emoji: '🚛', iconBg: '#E0F5F5',
    rating: 4.6, reviews: [], usageCount: 38,
    videoUrl: vidUrl('12tmeAcojZHLPWi5NPZEGk'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'call-status-update',
    name: 'Call Check / Status Update Agent',
    tagline: 'Get shipment status and ETA with a simple conversational check',
    description: 'Provides the status and estimated time of arrival of shipments through a simple conversational interface—eliminating manual tracking calls and keeping teams informed in real time.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'TLX',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Shipment', 'Status', 'ETA', 'Tracking'],
    emoji: '📞', iconBg: '#E0F5F5',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'carrier-pricing-validation',
    name: 'Carrier Pricing Validation Agent',
    tagline: 'Translate pricing agreements to structured contract data for validation',
    description: 'Translates pricing agreement documents into structured contract JSON or SQL values for validation and entry—ensuring carrier contracts are accurately reflected in the TMS.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'TLX',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Carrier', 'Pricing', 'Contract', 'TMS'],
    emoji: '📑', iconBg: '#E0F5F5',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'dot-trucker-safety',
    name: 'DOT Trucker Safety Lookup Agent',
    tagline: 'Look up and validate DOT safety ratings for trucking carriers',
    description: 'Provides recommended safety ratings by looking up DOT compliance information for trucking carriers—helping logistics teams vet carriers and maintain regulatory compliance.',
    industry: ['Food & Beverage'], function: 'Compliance', productLine: 'TLX',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['DOT', 'Safety Rating', 'Carrier', 'Compliance'],
    emoji: '🚛', iconBg: '#E0F5F5',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },

  // ── TRAVERSE GLOBAL ───────────────────────────────────────────────────────────

  {
    id: 'fulfillment-picking',
    name: 'Fulfillment and Picking Agent',
    tagline: 'Optimize order fulfillment with efficient pick sequences and allocation strategies',
    description: 'Optimizes order fulfillment and picking workflows by recommending the most efficient pick sequences and allocation strategies across open orders.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Traverse Global',
    status: 'live', flowId: 'placeholder',
    tags: ['Fulfillment', 'Picking', 'Warehouse', 'Allocation'],
    emoji: '📦', iconBg: '#E1F5EE',
    rating: 4.7, reviews: [], usageCount: 44,
    videoUrl: vidUrl('WSp48K4DEnZZmGPe1iynKj'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'plan-then-execute',
    name: 'Plan Then Execute Agent',
    tagline: 'Generate and sequence production schedules based on capacity, due dates, and materials',
    description: 'Generates and sequences production schedules based on resource capacity, due dates, and material availability, then guides execution through actionable step-by-step plans.',
    industry: ['Food & Beverage'], function: 'Supply Chain / Planning', productLine: 'Traverse Global',
    status: 'live', flowId: 'placeholder',
    tags: ['Production Schedule', 'Capacity', 'Planning'],
    emoji: '📅', iconBg: '#E1F5EE',
    rating: 4.8, reviews: [], usageCount: 57,
    videoUrl: vidUrl('xSqJvFQmzp7R71xa955guf'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'purchasing-traverse',
    name: 'Purchasing Agent',
    tagline: 'Flag late POs, send supplier reminders, and surface actionable procurement tasks',
    description: 'Manages the purchase order workspace by flagging late POs, sending supplier reminders, and surfacing actionable procurement tasks to keep supply timelines on track.',
    industry: ['Food & Beverage'], function: 'Procurement', productLine: 'Traverse Global',
    status: 'live', flowId: 'placeholder',
    tags: ['Purchase Orders', 'Procurement', 'Supplier', 'PO Tracking'],
    emoji: '🛒', iconBg: '#FAEEDA',
    rating: 4.6, reviews: [], usageCount: 39,
    videoUrl: vidUrl('jDbi3x9FtB389Xx7d6bZaB'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'sales-rep-agent',
    name: 'Sales Rep Agent',
    tagline: 'Assist sales reps with quotes, updates, and follow-up reminders',
    description: 'Assists sales representatives with quote creation, updates, and follow-up reminders to accelerate deal velocity and reduce manual administrative effort.',
    industry: ['Food & Beverage'], function: 'Sales / CRM', productLine: 'Traverse Global',
    status: 'live', flowId: 'placeholder',
    tags: ['Sales', 'Quotes', 'CRM', 'Follow-up'],
    emoji: '🎯', iconBg: '#FBEAF0',
    rating: 4.7, reviews: [], usageCount: 48,
    videoUrl: vidUrl('bnRFiA62eEgNu92M4NjcxM'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'safety-stock-traverse',
    name: 'Safety Stock & Lead Time Analysis Agent',
    tagline: 'Evaluate safety stock and lead times with 12 months of real ERP data',
    description: 'Connects directly to your ERP data to evaluate whether current safety stock levels and lead times still reflect reality. Pulls 12 months of demand history, applies statistical safety stock formulas at a 95% service level, and tells you what to change and why—with specific numbers, not generalities.',
    industry: ['Food & Beverage'], function: 'Supply Chain / Planning', productLine: 'Traverse Global',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Safety Stock', 'Lead Time', 'Statistical', 'ERP'],
    emoji: '📊', iconBg: '#E1F5EE',
    rating: 4.8, reviews: [], usageCount: 18,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },

  // ── MADE2MANAGE ───────────────────────────────────────────────────────────────

  {
    id: 'abc-code-classification',
    name: 'ABC Code Classification Agent',
    tagline: 'Reclassify ABC inventory codes using actual demand-driven value',
    description: 'Reclassifies ABC inventory codes using actual demand-driven value, enabling planners to prioritize high-impact items and optimize replenishment effort across the inventory base.',
    industry: ['Food & Beverage'], function: 'Supply Chain / Planning', productLine: 'Made2Manage',
    status: 'live', flowId: 'placeholder',
    tags: ['ABC Analysis', 'Inventory', 'Classification', 'Replenishment'],
    emoji: '🔢', iconBg: '#E1F5EE',
    rating: 4.6, reviews: [], usageCount: 31,
    videoUrl: vidUrl('pocBwRMGb4k3grWB1rqttK'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'safety-stock-lead-time',
    name: 'Safety Stock & Lead Time Analysis Agent',
    tagline: 'Generate data-driven safety stock recommendations from 12 months of demand data',
    description: 'Evaluates 12 months of demand variability, supplier and manufacturing lead-time performance, and stockout history to generate data-driven safety stock recommendations with transparent rationale and confidence levels.',
    industry: ['Food & Beverage'], function: 'Supply Chain / Planning', productLine: 'Made2Manage',
    status: 'live', flowId: 'placeholder',
    tags: ['Safety Stock', 'Lead Time', 'Demand Variability', 'M2M'],
    emoji: '📊', iconBg: '#E1F5EE',
    rating: 4.8, reviews: [], usageCount: 43,
    videoUrl: vidUrl('t5PzKAJw3W2wwMGLBiJ13i'), docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'notify-late-pos',
    name: 'Notify Late POs Agent',
    tagline: 'Prioritize timely delivery and ensure lead times do not exceed thresholds',
    description: 'Helps in prioritizing the timely delivery of items, making sure lead times do not exceed thresholds by automatically notifying teams of late or at-risk purchase orders.',
    industry: ['Food & Beverage'], function: 'Procurement', productLine: 'Made2Manage',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Purchase Orders', 'Late POs', 'Notifications', 'Lead Time'],
    emoji: '⚠️', iconBg: '#FAEEDA',
    rating: 4.5, reviews: [], usageCount: 12,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },

  // ── EQUIPMENT DMS ─────────────────────────────────────────────────────────────

  {
    id: 'damage-detection-bc',
    name: 'Damage Detection Agent (BC)',
    tagline: 'Analyze equipment physical damage and estimate repair cost via Business Central',
    description: 'Quick and easy analysis of equipment physical damage. Provides an estimated repair cost, parts required for repair, and approximate labor hours—embedded directly in Business Central.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Equipment DMS',
    status: 'live', flowId: 'placeholder',
    tags: ['Damage Detection', 'Repair', 'Equipment', 'Business Central'],
    emoji: '🔧', iconBg: '#FAEEDA',
    rating: 4.7, reviews: [], usageCount: 36,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'damage-detection-standalone',
    name: 'Damage Detection Agent (Standalone)',
    tagline: 'Analyze equipment physical damage and estimate repair cost via standalone interface',
    description: 'Quick and easy analysis of equipment physical damage. Provides an estimated repair cost, parts required for repair, and approximate labor hours through a standalone interface accessible outside of Business Central.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Equipment DMS',
    status: 'live', flowId: 'placeholder',
    tags: ['Damage Detection', 'Repair', 'Equipment', 'Standalone'],
    emoji: '🔧', iconBg: '#FAEEDA',
    rating: 4.6, reviews: [], usageCount: 28,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'auto-fill-attributes-bc',
    name: 'Auto-Fill Attributes Agent (BC)',
    tagline: 'Auto-fill equipment specifications from OEM sheets via Business Central',
    description: 'Utilizes OEM specification sheets or product catalogs to auto-fill all available specifications and attributes for equipment in inventory—embedded in Business Central.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Equipment DMS',
    status: 'live', flowId: 'placeholder',
    tags: ['Auto-Fill', 'OEM', 'Specifications', 'Business Central'],
    emoji: '⚙️', iconBg: '#FAEEDA',
    rating: 4.7, reviews: [], usageCount: 32,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'auto-fill-attributes-standalone',
    name: 'Auto-Fill Attributes Agent (Standalone)',
    tagline: 'Auto-fill equipment specifications from OEM sheets via standalone interface',
    description: 'Utilizes OEM specification sheets or product catalogs to auto-fill all available specifications and attributes for equipment in inventory through a standalone interface.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Equipment DMS',
    status: 'live', flowId: 'placeholder',
    tags: ['Auto-Fill', 'OEM', 'Specifications', 'Standalone'],
    emoji: '⚙️', iconBg: '#FAEEDA',
    rating: 4.6, reviews: [], usageCount: 25,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'item-recommendation',
    name: 'Item Recommendation Agent',
    tagline: 'Recommend cross-sell items using sales history and inventory data',
    description: 'Recommends items for cross-selling by utilizing sales history and item inventory. Actions taken by the sales person on recommended items are sent back to improve future recommendations.',
    industry: ['Food & Beverage'], function: 'Sales / CRM', productLine: 'Equipment DMS',
    status: 'live', flowId: 'placeholder',
    tags: ['Cross-Sell', 'Recommendations', 'Sales History', 'Inventory'],
    emoji: '💡', iconBg: '#FBEAF0',
    rating: 4.5, reviews: [], usageCount: 22,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'pdf-configuration-import',
    name: 'PDF Configuration Import Agent',
    tagline: 'Upload equipment configuration PDFs and generate structured import proposals',
    description: 'Upload the manufacturer\'s equipment configuration PDF via BC, extract it via AppCentral, and generate an import proposal with structured, ready-to-use configuration data.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Equipment DMS',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['PDF', 'Configuration', 'Import', 'Equipment'],
    emoji: '📄', iconBg: '#FAEEDA',
    rating: 4.5, reviews: [], usageCount: 8,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'known-bug-agent',
    name: 'Known Bug Agent',
    tagline: 'Analyze BC user errors against known issues and provide workarounds',
    description: 'Analyzes Business Central user errors for known issues in DevOps and provides recommendations and workarounds to resolve problems quickly without escalating to support.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Equipment DMS',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Bug', 'DevOps', 'Workaround', 'Support'],
    emoji: '🐛', iconBg: '#FAEEDA',
    rating: 4.4, reviews: [], usageCount: 6,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'damage-detection-equipsoft',
    name: 'Damage Detection Agent (Equipsoft)',
    tagline: 'Analyze equipment damage and estimate repair cost via Equipsoft',
    description: 'Quick and easy analysis of equipment physical damage via Equipsoft. Provides an estimated repair cost, parts required for repair, and approximate labor hours.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Equipsoft',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Damage Detection', 'Equipsoft', 'Repair', 'Equipment'],
    emoji: '🔧', iconBg: '#FEF3C7',
    rating: 4.4, reviews: [], usageCount: 5,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },

  // ── LOGILITY - DAI+ ───────────────────────────────────────────────────────────

  {
    id: 'detect-trends',
    name: 'Detect Trends Agent',
    tagline: 'Review and surface trends hidden in historical demand data',
    description: 'Analyzes historical demand data to surface actionable trend signals—identifying growth patterns, seasonal shifts, and anomalies that help planners make better forecasting decisions.',
    industry: ['Food & Beverage'], function: 'Analytics', productLine: 'Logility - DAI+',
    status: 'live', flowId: 'placeholder',
    tags: ['Trends', 'Demand', 'History', 'Forecasting'],
    emoji: '📈', iconBg: '#E6F1FB',
    rating: 4.6, reviews: [], usageCount: 34,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'training-opportunities',
    name: 'Training Opportunities Agent',
    tagline: 'Retrieve and review available training opportunities within Logility',
    description: 'Retrieves and presents training opportunities within the Logility platform, helping users discover relevant courses, certifications, and skill-building resources to maximize their planning capabilities.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Logility - DAI+',
    status: 'live', flowId: 'placeholder',
    tags: ['Training', 'Learning', 'Logility', 'Courses'],
    emoji: '🎓', iconBg: '#E6F1FB',
    rating: 4.4, reviews: [], usageCount: 19,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'retrieve-history-forecast',
    name: 'Retrieve History & Forecast Agent',
    tagline: 'Pull historical data and current forecasts for demand planning analysis',
    description: 'Retrieves historical demand data and current forecast figures from Logility to support demand planning analysis, consensus meetings, and performance reviews.',
    industry: ['Food & Beverage'], function: 'Supply Chain / Planning', productLine: 'Logility - DAI+',
    status: 'live', flowId: 'placeholder',
    tags: ['History', 'Forecast', 'Demand Planning', 'Logility'],
    emoji: '📊', iconBg: '#E6F1FB',
    rating: 4.6, reviews: [], usageCount: 28,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'review-forecast-accuracy',
    name: 'Review Forecast Accuracy Agent',
    tagline: 'Analyze forecast accuracy metrics and identify areas for improvement',
    description: 'Reviews forecast accuracy metrics across items, locations, and time horizons—identifying bias, MAPE trends, and improvement opportunities to continuously sharpen planning performance.',
    industry: ['Food & Beverage'], function: 'Analytics', productLine: 'Logility - DAI+',
    status: 'live', flowId: 'placeholder',
    tags: ['Forecast Accuracy', 'MAPE', 'Bias', 'Logility'],
    emoji: '🎯', iconBg: '#E6F1FB',
    rating: 4.7, reviews: [], usageCount: 31,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },

  // ── OXAION ERP ────────────────────────────────────────────────────────────────

  {
    id: 'customer-datasheet',
    name: 'Customer Datasheet Agent',
    tagline: 'Prepare customer appointment briefs and visit datasheets automatically',
    description: 'Automatically prepares customer datasheets and appointment briefs by pulling together relevant customer data, recent order history, open issues, and key account metrics before visits.',
    industry: ['Food & Beverage'], function: 'Sales / CRM', productLine: 'oxaion ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Customer', 'Datasheet', 'Sales', 'Account Management'],
    emoji: '📋', iconBg: '#ECFEFF',
    rating: 4.6, reviews: [], usageCount: 27,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'keyword-indexing',
    name: 'Keyword Indexing Agent',
    tagline: 'Automatically index documents in the DMS with intelligent keyword tagging',
    description: 'Automatically indexes documents in the Document Management System with intelligent keyword tagging, improving searchability and reducing time spent locating critical business documents.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'oxaion ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['DMS', 'Indexing', 'Keywords', 'Documents'],
    emoji: '🔖', iconBg: '#ECFEFF',
    rating: 4.5, reviews: [], usageCount: 22,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'natural-language-search',
    name: 'Natural Language Search Agent',
    tagline: 'Select and filter ERP data using plain natural language queries',
    description: 'Enables users to select and filter data from oxaion ERP using plain natural language queries, removing the need to know complex filter syntax or report structures.',
    industry: ['Food & Beverage'], function: 'Analytics', productLine: 'oxaion ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Natural Language', 'Search', 'NLP', 'Query'],
    emoji: '🔍', iconBg: '#ECFEFF',
    rating: 4.7, reviews: [], usageCount: 41,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'patch-notes',
    name: 'Patch Notes Agent',
    tagline: 'Get an instant overview of ERP changes across versions',
    description: 'Provides ERP administrators and key users with an instant, conversational overview of changes introduced in each ERP version—eliminating the need to parse lengthy release notes manually.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'oxaion ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Patch Notes', 'Release', 'ERP Updates', 'Admin'],
    emoji: '📝', iconBg: '#ECFEFF',
    rating: 4.4, reviews: [], usageCount: 18,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'smart-inbox',
    name: 'Smart Inbox Agent',
    tagline: 'Automate incoming mail processing with intelligent follow-up actions',
    description: 'Automates incoming mail processing with intelligent follow-up actions—classifying emails, routing them to the correct handler, and triggering ERP workflows based on content.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'oxaion ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Email', 'Inbox', 'Automation', 'Routing'],
    emoji: '📬', iconBg: '#ECFEFF',
    rating: 4.6, reviews: [], usageCount: 33,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'variant-formula-analyzer',
    name: 'Variant Formula Analyzer Agent',
    tagline: 'Create formula syntax for article variants in oxaion ERP',
    description: 'Creates and validates formula syntax for article variants in oxaion ERP, helping configuration specialists define complex variant rules accurately and efficiently.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'oxaion ERP',
    status: 'live', flowId: 'placeholder',
    tags: ['Variants', 'Formula', 'Configuration', 'oxaion'],
    emoji: '🧮', iconBg: '#ECFEFF',
    rating: 4.5, reviews: [], usageCount: 16,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },

  // ── INTUITIVE ─────────────────────────────────────────────────────────────────

  {
    id: 'inventory-abc-analysis',
    name: 'Inventory ABC Analysis Agent',
    tagline: 'Classify inventory by value and activity for smarter replenishment decisions',
    description: 'Classifies inventory items into ABC tiers based on demand value and activity, enabling planners to focus replenishment effort on high-impact items and streamline low-velocity stock management.',
    industry: ['Food & Beverage'], function: 'Supply Chain / Planning', productLine: 'Intuitive',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['ABC Analysis', 'Inventory', 'Classification', 'Replenishment'],
    emoji: '🔢', iconBg: '#E1F5EE',
    rating: 4.5, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'late-purchase-orders',
    name: 'Late Purchase Orders Agent',
    tagline: 'Surface and action late purchase orders before they impact production',
    description: 'Automatically surfaces late and at-risk purchase orders, flags supplier delays, and recommends expediting actions before they impact production schedules or customer commitments.',
    industry: ['Food & Beverage'], function: 'Procurement', productLine: 'Intuitive',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Late POs', 'Purchase Orders', 'Expediting', 'Procurement'],
    emoji: '⚠️', iconBg: '#FAEEDA',
    rating: 4.5, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'safety-stock-optimization',
    name: 'Safety Stock Optimization Agent',
    tagline: 'Optimize safety stock levels across the portfolio to balance service and cost',
    description: 'Optimizes safety stock levels across the product portfolio, balancing service level targets against carrying cost constraints to right-size buffer inventory across all SKUs and locations.',
    industry: ['Food & Beverage'], function: 'Supply Chain / Planning', productLine: 'Intuitive',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Safety Stock', 'Optimization', 'Service Level', 'Carrying Cost'],
    emoji: '📊', iconBg: '#E1F5EE',
    rating: 4.5, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },

  // ── MISTRAL ERP ───────────────────────────────────────────────────────────────

  {
    id: 'mistral-spare-parts',
    name: 'Mistral Spare Part Catalog Update Agent',
    tagline: 'Automatically integrate and update parts catalog with intelligent column mapping',
    description: 'Automates the integration and updating of the spare parts catalog in Mistral ERP with intelligent column mapping—eliminating manual data entry and ensuring catalog accuracy.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Mistral ERP',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Spare Parts', 'Catalog', 'Automation', 'Mistral'],
    emoji: '🔩', iconBg: '#FAF5FF',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'mistral-advanced-search',
    name: 'Mistral Advanced Search Agent',
    tagline: 'Global search tool for finding any data across Mistral ERP instantly',
    description: 'Provides a global search capability across Mistral ERP, enabling users to instantly locate any record, document, or data point without navigating complex menu structures.',
    industry: ['Food & Beverage'], function: 'Analytics', productLine: 'Mistral ERP',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Search', 'Global', 'Mistral', 'ERP'],
    emoji: '🔍', iconBg: '#FAF5FF',
    rating: 4.5, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'mistral-online-help',
    name: 'Mistral Intelligent Online Help Agent',
    tagline: 'Contextual help and guidelines when using Mistral ERP',
    description: 'Provides contextual online help and guidelines through a chatbot interface embedded in Mistral ERP—answering how-to questions, explaining features, and guiding users through complex workflows.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Mistral ERP',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Help', 'Chatbot', 'Mistral', 'User Guide'],
    emoji: '💬', iconBg: '#FAF5FF',
    rating: 4.5, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'mistral-route-sales',
    name: 'Mistral Smart Route Planning — Sales',
    tagline: 'Optimize sales routes to maximize coverage and minimize travel time',
    description: 'Optimizes sales routes across territories to maximize customer coverage, minimize travel time, and increase the number of productive sales calls per day.',
    industry: ['Food & Beverage'], function: 'Sales / CRM', productLine: 'Mistral ERP',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Route Planning', 'Sales', 'Territory', 'Optimization'],
    emoji: '🗺️', iconBg: '#FAF5FF',
    rating: 4.5, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'mistral-route-transport',
    name: 'Mistral Smart Route Planning — Transport',
    tagline: 'Optimize transportation routes to reduce delivery cost and time',
    description: 'Optimizes transportation routes to reduce delivery cost, fuel consumption, and transit time—improving delivery reliability and carrier efficiency across the distribution network.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Mistral ERP',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Route Planning', 'Transport', 'Delivery', 'Logistics'],
    emoji: '🚛', iconBg: '#FAF5FF',
    rating: 4.5, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },

  // ── PARAGON ───────────────────────────────────────────────────────────────────

  {
    id: 'resource-availability',
    name: 'Resource Availability Agent',
    tagline: 'Surface real-time resource availability for transport and logistics planning',
    description: 'Surfaces real-time resource availability across the transport and logistics network, helping planners match capacity to demand and prevent bottlenecks before they occur.',
    industry: ['Food & Beverage'], function: 'Supply Chain / Planning', productLine: 'Paragon',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Resources', 'Availability', 'Transport', 'Capacity'],
    emoji: '📅', iconBg: '#E6F1FB',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },

  // ── ROSS ──────────────────────────────────────────────────────────────────────

  {
    id: 'customer-trend-warning',
    name: 'Customer Trend & Early Warning Agent',
    tagline: 'Monitor customer purchasing behavior for early signs of revenue decline',
    description: 'Continuously monitors customer purchasing behavior to detect early signs of revenue decline, ordering slowdown, or full inactivity. Analyzes historical and current sales data by customer and by part, provides risk classification and explainable insights so sales teams can proactively engage customers before revenue is lost.',
    industry: ['Food & Beverage'], function: 'Sales / CRM', productLine: 'Ross',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Customer', 'Trend', 'Early Warning', 'Revenue Risk'],
    emoji: '📉', iconBg: '#FBEAF0',
    rating: 4.7, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'inventory-lot-risk',
    name: 'Inventory Lot Risk Agent',
    tagline: 'Track inventory nearing expiration and recommend reallocation or disposal',
    description: 'Proactively tracks inventory nearing expiration, identifies impacted lots, and recommends actions such as reallocation, priority usage, or disposal. Continuously scans inventory and predicts expiry risk based on usage rates and remaining shelf life.',
    industry: ['Food & Beverage'], function: 'Supply Chain / Planning', productLine: 'Ross',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Lot Risk', 'Expiration', 'Inventory', 'Shelf Life'],
    emoji: '⏰', iconBg: '#FCEBEB',
    rating: 4.6, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'safety-stock-ross',
    name: 'Safety Stock Optimization Agent',
    tagline: 'Optimize safety stock levels for Ross ERP with the AIaaS team',
    description: 'Optimizes safety stock levels across the product portfolio for Ross ERP, working with the AIaaS team to balance service level targets against carrying cost constraints.',
    industry: ['Food & Beverage'], function: 'Supply Chain / Planning', productLine: 'Ross',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Safety Stock', 'Optimization', 'Ross', 'AIaaS'],
    emoji: '📊', iconBg: '#FEF2F2',
    rating: 4.5, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },

  // ── RS2 ───────────────────────────────────────────────────────────────────────

  {
    id: 'incoming-invoice-accounting',
    name: 'Incoming Invoice Accounting Agent',
    tagline: 'Automatically assign accounts for incoming invoices with delivery note checks',
    description: 'Automates account assignment for incoming invoices, including delivery note checks for documents—reducing manual coding effort and accelerating the AP posting cycle.',
    industry: ['Food & Beverage'], function: 'Finance / AR', productLine: 'rs2',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Invoices', 'Accounts Payable', 'Automation', 'rs2'],
    emoji: '🧾', iconBg: '#ECFEFF',
    rating: 4.5, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'payment-allocation',
    name: 'Payment Allocation Agent',
    tagline: 'Auto-detect customer numbers and posting info from payment references',
    description: 'Automatically detects customer numbers, G/L accounts, and posting information from payment references—eliminating manual allocation effort and reducing posting errors.',
    industry: ['Food & Beverage'], function: 'Finance / AR', productLine: 'rs2',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Payment', 'Allocation', 'G/L', 'Posting'],
    emoji: '💰', iconBg: '#ECFEFF',
    rating: 4.5, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'email-to-quote',
    name: 'Email to Quote Agent',
    tagline: 'Automatically create quotes from inbound emails with order history references',
    description: 'Automatically creates quotes from inbound emails, including references to previous orders—reducing response time and ensuring consistent, accurate quoting without manual data entry.',
    industry: ['Food & Beverage'], function: 'Sales / CRM', productLine: 'rs2',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Email', 'Quote', 'Automation', 'Sales'],
    emoji: '📧', iconBg: '#FBEAF0',
    rating: 4.5, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'master-data-autofill',
    name: 'Master Data Autofill Agent',
    tagline: 'Auto-create and enrich customer, vendor, and product master data with SEO texts',
    description: 'Automatically creates and enriches customer, vendor, and product master data including SEO texts—ensuring complete, consistent records across the ERP without manual data entry.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'rs2',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Master Data', 'Autofill', 'Enrichment', 'SEO'],
    emoji: '🗃️', iconBg: '#ECFEFF',
    rating: 4.5, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'dms-checkin',
    name: 'DMS Check-In Agent',
    tagline: 'Automatically scan mailboxes, check-in documents, and apply object-based tagging',
    description: 'Automatically scans mailboxes, performs DMS check-in, and applies object-based tagging—ensuring every incoming document is captured, classified, and filed without manual intervention.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'rs2',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['DMS', 'Email', 'Tagging', 'Document Management'],
    emoji: '📁', iconBg: '#ECFEFF',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'job-time-recording',
    name: 'Job & Time Recording Agent',
    tagline: 'Automatically post job times to the time tracking system',
    description: 'Automatically posts job times to the time tracking system—reducing manual timesheet entry, improving accuracy, and ensuring labor costs are captured against the correct jobs.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'rs2',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Time Tracking', 'Jobs', 'Posting', 'Labor'],
    emoji: '⏱️', iconBg: '#ECFEFF',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'financial-accounting-info',
    name: 'Financial Accounting Info Agent',
    tagline: 'Answer questions about customer balances, invoices, and payment receipts',
    description: 'Provides information about customer balances, outstanding invoices, and upcoming payment receipts—giving finance teams instant answers without running manual reports.',
    industry: ['Food & Beverage'], function: 'Finance / AR', productLine: 'rs2',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Finance', 'Balances', 'Invoices', 'Payments'],
    emoji: '💳', iconBg: '#EEEDFE',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'financial-accounting-document',
    name: 'Financial Accounting Document Assistant',
    tagline: 'Upload receipts via mobile and post directly to the appropriate accounts',
    description: 'Receipts are uploaded via mobile phone or app and posted directly to the appropriate accounts in the ERP—eliminating paper-based expense workflows and accelerating month-end close.',
    industry: ['Food & Beverage'], function: 'Finance / AR', productLine: 'rs2',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Receipts', 'Mobile', 'Posting', 'Accounting'],
    emoji: '📱', iconBg: '#EEEDFE',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },

  // ── SOUTHWARE ─────────────────────────────────────────────────────────────────

  {
    id: 'ar-collections',
    name: 'AR Collections Agent',
    tagline: 'Streamline accounts receivable collections with intelligent follow-up workflows',
    description: 'Streamlines accounts receivable collections by identifying overdue accounts, prioritizing follow-up actions, and automating reminder communications to improve cash flow.',
    industry: ['Food & Beverage'], function: 'Finance / AR', productLine: 'Southware',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['AR', 'Collections', 'Overdue', 'Cash Flow'],
    emoji: '💳', iconBg: '#EEEDFE',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'customer-engagement',
    name: 'Customer Engagement Agent',
    tagline: 'Proactively engage customers with insights drawn from order and account data',
    description: 'Proactively engages customers by surfacing relevant insights from order history, account activity, and relationship data—helping sales and service teams deliver timely, personalized outreach.',
    industry: ['Food & Beverage'], function: 'Sales / CRM', productLine: 'Southware',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Customer', 'Engagement', 'CRM', 'Outreach'],
    emoji: '🤝', iconBg: '#FBEAF0',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'inventory-balance',
    name: 'Inventory Balance Agent',
    tagline: 'Surface on-hand inventory balances and availability across locations',
    description: 'Surfaces accurate on-hand inventory balances and availability across locations, helping operations and sales teams answer availability questions instantly without manual lookups.',
    industry: ['Food & Beverage'], function: 'Supply Chain / Planning', productLine: 'Southware',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Inventory', 'Balance', 'On-Hand', 'Availability'],
    emoji: '📦', iconBg: '#E1F5EE',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'order-engagement',
    name: 'Order Engagement Agent',
    tagline: 'Provide real-time order status and proactive alerts on open orders',
    description: 'Provides real-time order status and proactive engagement on open orders—alerting teams to delays, changes, and actions needed to keep orders on track.',
    industry: ['Food & Beverage'], function: 'Sales / CRM', productLine: 'Southware',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Orders', 'Status', 'Engagement', 'Alerts'],
    emoji: '📋', iconBg: '#FBEAF0',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'service-engagement',
    name: 'Service Engagement Agent',
    tagline: 'Surface next-best actions and open service requests for service teams',
    description: 'Manages service interactions by surfacing next-best actions, open service requests, and customer history—helping service teams resolve issues faster and improve customer satisfaction.',
    industry: ['Food & Beverage'], function: 'Sales / CRM', productLine: 'Southware',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Service', 'Engagement', 'CRM', 'Service Requests'],
    emoji: '🎯', iconBg: '#FBEAF0',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'service-order-solution',
    name: 'Service Order Solution Agent',
    tagline: 'Resolve service orders faster with diagnosis and solution recommendations',
    description: 'Accelerates service order resolution by diagnosing reported issues, recommending proven solutions from historical data, and guiding technicians through structured resolution workflows.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Southware',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Service Orders', 'Resolution', 'Diagnosis', 'Technician'],
    emoji: '🔧', iconBg: '#FAEEDA',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'vendor-engagement',
    name: 'Vendor Engagement Agent',
    tagline: 'Proactively engage vendors on orders, delivery timelines, and performance',
    description: 'Proactively engages vendors on open purchase orders, delivery timelines, and performance metrics—reducing the manual effort of supplier communication and keeping procurement teams informed.',
    industry: ['Food & Beverage'], function: 'Procurement', productLine: 'Southware',
    status: 'coming-soon', flowId: 'placeholder',
    tags: ['Vendor', 'Procurement', 'Supplier', 'Communication'],
    emoji: '🏭', iconBg: '#FAEEDA',
    rating: 4.4, reviews: [], usageCount: 0,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },

  // ── BUSINESS CENTRAL (standalone BC agents) ───────────────────────────────────

  {
    id: 'ar-aging',
    name: 'AR Aging Agent',
    tagline: 'Instant AR aging analysis and customer balance intelligence for Business Central',
    description: 'Delivers instant accounts receivable aging analysis directly from Business Central—surfacing overdue balances, customer payment trends, and collection priorities so finance teams can act on the highest-risk accounts first.',
    industry: ['Food & Beverage'], function: 'Finance / AR', productLine: 'Business Central',
    status: 'live', flowId: 'd383b17f-35d5-4ce6-b96d-c5850cfe10c7',
    tags: ['AR Ledger', 'Customer Table', 'Aging', 'Collections'],
    emoji: '💳', iconBg: '#EEEDFE',
    rating: 4.8,
    reviews: [
      { author: 'Finance Director, Aptean Customer', stars: 5, comment: 'Cuts our monthly AR review from half a day to under 10 minutes.' },
      { author: 'Controller, Food Manufacturer', stars: 5, comment: 'Finally a way to get aging out of BC without exporting to Excel.' },
    ],
    usageCount: 142,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: true,
  },
  {
    id: 'ar-balance-traverse',
    name: 'AR Balance Agent',
    tagline: 'API-driven Accounts Receivable insights for Business Central customers',
    description: 'Provides accurate, API-driven Accounts Receivable insights for customers in Business Central. Answers questions related to sales, payments received, outstanding balances, recent payments, and overdue exposure using verified Customer data. Drills down into Customer Ledger Entries for transaction-level clarity.',
    industry: ['Food & Beverage'], function: 'Finance / AR', productLine: 'Business Central',
    status: 'live', flowId: 'placeholder',
    tags: ['AR', 'Accounts Receivable', 'Business Central', 'Balance'],
    emoji: '💳', iconBg: '#EEEDFE',
    rating: 4.7, reviews: [], usageCount: 34,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'inventory-traverse',
    name: 'Inventory Insights Agent',
    tagline: 'Inventory aging, on-hand quantity, and value insights from Business Central',
    description: 'Provides accurate inventory aging, on-hand quantity, and inventory value insights using verified Business Central Item data. Explains why aging or quantity patterns exist only when explicitly requested, using Item Ledger Entries.',
    industry: ['Food & Beverage'], function: 'Supply Chain / Planning', productLine: 'Business Central',
    status: 'live', flowId: 'placeholder',
    tags: ['Inventory', 'Aging', 'On-Hand', 'Business Central'],
    emoji: '📦', iconBg: '#E1F5EE',
    rating: 4.6, reviews: [], usageCount: 29,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'margin-traverse',
    name: 'Margin Intelligence Agent',
    tagline: 'Executive-grade margin and profitability insights from Business Central data',
    description: 'Transforms Business Central API data into executive-grade business insights across sales, revenue, margin, quantity, customer performance, item/style performance, trends, profitability, operational issues, bottlenecks, and opportunities.',
    industry: ['Food & Beverage'], function: 'Analytics', productLine: 'Business Central',
    status: 'live', flowId: 'placeholder',
    tags: ['Margin', 'Profitability', 'Analytics', 'Business Central'],
    emoji: '📈', iconBg: '#E6F1FB',
    rating: 4.8, reviews: [], usageCount: 41,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'saleorder-24hrs',
    name: 'Sales Order 24-Hour Agent',
    tagline: 'Track sales order health, status, and shipments in business-friendly language',
    description: 'Retrieves sales order health, status, tracking, shipments, quantities, styles, colors, and dates from Business Central and explains it in clear business-friendly language. Powers interactive dashboards and daily scheduled reporting.',
    industry: ['Food & Beverage'], function: 'Sales / CRM', productLine: 'Business Central',
    status: 'live', flowId: 'placeholder',
    tags: ['Sales Orders', 'Shipment', 'Tracking', 'Dashboard'],
    emoji: '📋', iconBg: '#FBEAF0',
    rating: 4.6, reviews: [], usageCount: 37,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },
  {
    id: 'shipment-24hrs',
    name: 'Shipment 24-Hour Agent',
    tagline: 'Explain shipment activity from the last 24 hours including delivery risk',
    description: 'Pulls shipment activity from the last 24 hours and explains it in business-friendly language: what shipped, what is pending, delivery risk, and overall order health.',
    industry: ['Food & Beverage'], function: 'Operations', productLine: 'Business Central',
    status: 'live', flowId: 'placeholder',
    tags: ['Shipment', 'Delivery', 'Order Health', '24-Hour'],
    emoji: '🚛', iconBg: '#E0F5F5',
    rating: 4.5, reviews: [], usageCount: 28,
    videoUrl: '', docsUrl: '', reviewLinks: [], featured: false,
  },

];

// ── Write files ───────────────────────────────────────────────────────────────

if (!fs.existsSync(agentsDir)) fs.mkdirSync(agentsDir, { recursive: true });

const existingFiles = fs.readdirSync(agentsDir).filter(f => f.endsWith('.json'));
const newIds = new Set(agents.map(a => a.id));
let removed = 0;
for (const file of existingFiles) {
  const id = file.replace('.json', '');
  if (!newIds.has(id)) {
    fs.unlinkSync(path.join(agentsDir, file));
    removed++;
    console.log(`  ✗ Removed stale: ${file}`);
  }
}

let created = 0, updated = 0;
for (const agent of agents) {
  const filePath = path.join(agentsDir, `${agent.id}.json`);
  const existed = fs.existsSync(filePath);
  fs.writeFileSync(filePath, JSON.stringify(agent, null, 2));
  if (existed) updated++; else created++;
}

console.log(`\n✓ Done: ${created} created, ${updated} updated, ${removed} removed`);
console.log(`  Total agents: ${agents.length}`);
